### ISSUE TITLE
[Next.js] Module parse failed (solved)

### ISSUE THREAD

**Issue by nandorojo** [nandorojo/dripsy#149]
```sh
error - ../../node_modules/dripsy/node_modules/@dripsy/core/build/components/ScrollView.js
Module parse failed: Unexpected token (10:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const containerSx = props.contentContainerSx && sx(props.contentContainerSx);
|     const indicatorSx = props.indicatorSx && sx(props.indicatorSx);
>     return (<DripsyScrollView {...props} contentContainerStyle={props.contentContainerStyle && containerSx
|             ? [props.contentContainerStyle, containerSx]
|             : containerSx || props.contentContainerStyle} indicatorStyle={props.indicatorStyle && indicatorSx
(node:38093) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
info  - automatically enabled Fast Refresh for 1 custom loader
info  - automatically enabled Fast Refresh for 1 custom loader
wait  - compiling /_error...
```

# Solution ✅

You might be seeing this error if you just installed or upgraded Dripsy. Changes are, you did this:

```sh
yarn add dripsy
```

And then it broke. Shit, why? 

The reason is, you probably have `@dripsy/gradient` or another subpackage installed to. Be sure to install those too!

```sh
yarn add dripsy @dripsy/gradient
```

### Canary

If you upgraded Dripsy on Canary, using `yarn add dripsy@canary`, you just need to do the same for any subpackages you have:

```
yarn add dripsy@canary @dripsy/gradient@canary
```

And that's it 🥸

**Comment by broerjuang** [comment]
Just trying dripsy and doing like what @nandorojo suggested. But still having the same error. :(

**Comment by kameshdhana** [comment]
Can confirm this package installation doesn't resolve those errors

**Comment by nandorojo** [comment]
this solution is pretty outdated. please confirm that your gradient and dripsy versions are all the same

**Comment by nandorojo** [comment]
you may also need to use the new `transpilePackages` array

**Comment by kameshdhana** [comment]
Will try your solution and let you know the result
I'll provide my full configuration soon
Currently we have a mono repo which consist of expo for mobile & next JS for web

**Comment by VGerris** [comment]
Is there any proper documentation explaining this in detail ? I just got this error after upgrading to dripsy 4. The apps/next directory has a .babelrc.json which does not throw the above error but :
https://stackoverflow.com/questions/77862959/duplicate-self-prop
Either way I cannot get this resolved, because I don't currently understand what is happening precisely and why.
Time for a new mono repo with Expo SDK 52, latest Next.js , dripsy etc ?
I have it pretty much all working after many days of changing and fixing code so I may be able to contribute if this is resolved.

Code is mostly based on git from 22 that was linked in a youtube video explaining expo-router .
I had to update all the Expo code too, because something like (tabs)/(tabs).tsx is no longer allowed and using same name for folder doesn't work either but using _layout.tsx seems to be the way.
It's pretty challenging to keep a stack like this working and up to date, I hope someone can help with docs and be specific enough for starters too, so not : yarn add package-x , but something like - run yarn add package-x in the folder project/apps/expo ( because it is used in both that and apps/next , or is it ) ? Also good to know if the babel.config.js in the expo folder applies to the next foldere ( doesn't seem so ). 

I currently have very similar config in both bable config files but I don't understand where the problem with self prop comes from. 
Should I file a new issue for that here? thank you!

**Comment by nandorojo** [comment]
You can remove the Babel file

**Comment by VGerris** [comment]
> You can remove the Babel file

hi Fernando, thank you for your quick reply!

My .babelrc.json has the following content:
```
{
  "presets": [
    "next/babel",
    ["babel-preset-expo", { "jsxRuntime": "automatic" }]
  ],
  "plugins": [
    ["@babel/plugin-transform-class-properties", { "loose": true }],
    ["@babel/plugin-transform-private-methods", { "loose": true }],
    ["@babel/plugin-transform-private-property-in-object", { "loose": true }],
    "react-native-reanimated/plugin"
  ]
}
```

If I remove the .babelrc.json file from apps/next I get:

Build Error
Next.js (15.1.3)

Failed to compile
../../node_modules/dripsy/build/core/components/ScrollView.js

Module parse failed: Unexpected token (10:12)
|     const containerSx = props.contentContainerSx && sx(props.contentContainerSx);
|     const indicatorSx = props.indicatorSx && sx(props.indicatorSx);
>     return (<DripsyScrollView {...props} contentContainerStyle={props.contentContainerStyle && containerSx
|             ? [props.contentContainerStyle, containerSx]
|             : containerSx || props.contentContainerStyle} indicatorStyle={props.indicatorStyle && indicatorSx

This error occurred during the build process and can only be dismissed by fixing the error.

Which lead me here.
My next.config.js is:

```
const { withExpo } = require('@expo/next-adapter')
const withFonts = require('next-fonts')
const withImages = require('next-images')
const withPlugins = require('next-compose-plugins')
const withTM = require('next-transpile-modules')([
  'solito',
  'dripsy',
  '@dripsy/core',
  'moti',
  'app',
  'zeego',
])

/** @type {import('next').NextConfig} */
const nextConfig = {
  // reanimated (and thus, Moti) doesn't work with strict mode currently...
  // https://github.com/nandorojo/moti/issues/224
  // https://github.com/necolas/react-native-web/pull/2330
  // https://github.com/nandorojo/moti/issues/224
  // once that gets fixed, set this back to true
  reactStrictMode: false,
  webpack5: true,
  images: {
    disableStaticImages: true,
  },
}

const transform = withPlugins([withTM, withFonts, withImages, withExpo])

module.exports = function (name, { defaultConfig }) {
  return transform(name, {
    ...defaultConfig,
    ...nextConfig,
  })
}
```

If I have the babel rc file in place, I get:

 ○ Compiling /_error ...
 ⨯ ./pages/_app.tsx
SyntaxError: Duplicate __self prop found. You are most likely using the deprecated transform-react-jsx-self Babel plugin. Both __source and __self are automatically set when using the automatic runtime. Please remove transform-react-jsx-source and transform-react-jsx-self from your Babel config.
  22 |     <>
  23 |       <Head>
> 24 |         <title>Solito Example App</title>
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  25 |         <meta
  26 |           name="description"
  27 |           content="Expo + Next.js with Solito. By Fernando Rojo."
 GET / 500 in 4867ms
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: ENOENT: no such file or directory, rename '/Users/vincent/develop/testdev/nextjs-conf-22-example/apps/next/.next/cache/webpack/client-development-fallback/0.pack.gz_' -> '/Users/vincent/develop/testdev/nextjs-conf-22-example/apps/next/.next/cache/webpack/client-development

babel.config.js in the expo folder is :

```
module.exports = function (api) {
  api.cache(true)
  return {
    presets: [['babel-preset-expo', { jsxRuntime: 'automatic' }] /* , ['module:@react-native/babel-preset'] */ ],
    plugins: ['react-native-reanimated/plugin'],
  }
}
```

Any help is greatly appreciated.

Note that the native versions work pretty much, except for some routing issues that have to do with changes in expo-router.

Thank you for the help!

**Comment by nandorojo** [comment]
The next config file is very outdated. We no longer use transpile modules package, instead see my answer before your comment about

**Comment by nandorojo** [comment]
This might help:

https://github.com/nandorojo/solito/blob/master/example-monorepos/blank/apps/next/next.config.js

**Comment by VGerris** [comment]
hi, thank you again for the quick reply and detailing that out! And for your all your work and contributions for that matter, I can see how much time it takes to do and support!

I didn't understand from the comment what the difference was because it both says transpile :).
So I updated the config and get an interesting new error :

 ○ Compiling / ...
 ✓ Compiled / in 1351ms (1056 modules)
 ⨯ ReferenceError: Document is not defined
    at Document (pages/_document.tsx:14:15)
    at ./pages/_document.tsx (.next/server/pages/_document.js:22:1)
    at __webpack_require__ (.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (.next/server/pages/_document.js:72:39)
    at <unknown> (.next/server/pages/_document.js:73:104)
    at __webpack_require__.X (.next/server/webpack-runtime.js:185:21)
    at <unknown> (.next/server/pages/_document.js:73:47)
    at Object.<anonymous> (.next/server/pages/_document.js:76:3)
  12 | }
  13 |
> 14 | export default Document;
     |               ^ {
  page: '/'
}
 ○ Compiling /_error ...
 ✓ Compiled /_error in 625ms (1058 modules)
 ⨯ ReferenceError: Document is not defined
    at Document (pages/_document.tsx:14:15)
    at ./pages/_document.tsx (.next/server/pages/_document.js:22:1)
    at __webpack_require__ (.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (.next/server/pages/_document.js:72:39)
    at <unknown> (.next/server/pages/_document.js:73:104)
    at __webpack_require__.X (.next/server/webpack-runtime.js:185:21)
    at <unknown> (.next/server/pages/_document.js:73:47)
    at Object.<anonymous> (.next/server/pages/_document.js:76:3)
  12 | }
  13 |
> 14 | export default Document;
     |               ^
 GET / 500 in 2972ms
 ✓ Compiled in 138ms (486 modules)
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 ✓ Compiled / in 263ms (1058 modules)
 ⨯ ReferenceError: Document is not defined
    at Document (pages/_document.tsx:13:15)
    at ./pages/_document.tsx (.next/server/pages/_document.js:22:1)
    at __webpack_require__ (.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (.next/server/pages/_document.js:72:39)
    at <unknown> (.next/server/pages/_document.js:73:104)
    at __webpack_require__.X (.next/server/webpack-runtime.js:185:21)
    at <unknown> (.next/server/pages/_document.js:73:47)
    at Object.<anonymous> (.next/server/pages/_document.js:76:3)
  11 | }
  12 |
> 13 | export default Document;
     |               ^
  14 | {
  page: '/'
}
 ⨯ ReferenceError: Document is not defined
    at Document (pages/_document.tsx:13:15)
    at ./pages/_document.tsx (.next/server/pages/_document.js:22:1)
    at __webpack_require__ (.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (.next/server/pages/_document.js:72:39)
    at <unknown> (.next/server/pages/_document.js:73:104)
    at __webpack_require__.X (.next/server/webpack-runtime.js:185:21)
    at <unknown> (.next/server/pages/_document.js:73:47)
    at Object.<anonymous> (.next/server/pages/_document.js:76:3)
  11 | }
  12 |
> 13 | export default Document;
     |               ^
  14 |
 GET / 500 in 526ms
^C
vincent@VIGE-MacBook-Air nextjs-conf-22-example % 


vincent@VIGE-MacBook-Air nextjs-conf-22-example % 
vincent@VIGE-MacBook-Air nextjs-conf-22-example % yarn run web
yarn run v1.22.22
$ cd apps/next && yarn next
$ /Users/vincent/develop/testdev/nextjs-conf-22-example/node_modules/.bin/next
   ▲ Next.js 15.1.3
   - Local:        http://localhost:3000
   - Network:      http://10.20.101.67:3000

 ✓ Starting...
 ✓ Ready in 1238ms
 ○ Compiling /_error ...
 ✓ Compiled / in 2.2s (1058 modules)
 ⨯ ReferenceError: Document is not defined
    at Document (pages/_document.tsx:13:15)
    at ./pages/_document.tsx (.next/server/pages/_document.js:22:1)
    at __webpack_require__ (.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (.next/server/pages/_document.js:72:39)
    at <unknown> (.next/server/pages/_document.js:73:104)
    at __webpack_require__.X (.next/server/webpack-runtime.js:185:21)
    at <unknown> (.next/server/pages/_document.js:73:47)
    at Object.<anonymous> (.next/server/pages/_document.js:76:3)
  11 | }
  12 |
> 13 | export default Document;
     |               ^
  14 |
 ⨯ ReferenceError: Document is not defined
    at Document (pages/_document.tsx:13:15)
    at ./pages/_document.tsx (.next/server/pages/_document.js:22:1)
    at __webpack_require__ (.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (.next/server/pages/_document.js:72:39)
    at <unknown> (.next/server/pages/_document.js:73:104)
    at __webpack_require__.X (.next/server/webpack-runtime.js:185:21)
    at <unknown> (.next/server/pages/_document.js:73:47)
    at Object.<anonymous> (.next/server/pages/_document.js:76:3)
  11 | }
  12 |
> 13 | export default Document;
     |               ^
  14 | {
  page: '/'
}
 ⨯ ReferenceError: Document is not defined
    at Document (pages/_document.tsx:13:15)
    at ./pages/_document.tsx (.next/server/pages/_document.js:22:1)
    at __webpack_require__ (.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (.next/server/pages/_document.js:72:39)
    at <unknown> (.next/server/pages/_document.js:73:104)
    at __webpack_require__.X (.next/server/webpack-runtime.js:185:21)
    at <unknown> (.next/server/pages/_document.js:73:47)
    at Object.<anonymous> (.next/server/pages/_document.js:76:3)
  11 | }
  12 |
> 13 | export default Document;
     |               ^
  14 |
 GET / 500 in 2267ms
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: ENOENT: no such file or directory, rename '/Users/vincent/develop/testdev/nextjs-conf-22-example/apps/next/.next/cache/webpack/client-development-fallback/0.pack.gz_' -> '/Users/vincent/develop/testdev/nextjs-conf-22-example/apps/next/.next/cache/webpack/client-development-fallback/0.pack.gz'

I have actually been trying to upgrade your repo here : https://github.com/nandorojo/nextjs-conf-22-example and comparing with your recent monorepo example :  https://github.com/nandorojo/solito/tree/master/example-monorepos/with-expo-router .

Feels I'm getting closer, although I had to make a lot of changes ( that I hope I can contribute ).
It's very hard to find some specific setup related documentation, so I am really greatful you spend your time helping out!

**Comment by VGerris** [comment]
by the way, I tried removing the .next folder and reran : yarn run web from the main folder, got the same issue.
The _document.tsx doesn't show any errors in vscodium and next/pages/_document.tsx holds:
```

/// <reference types="react" />
import NextDocument from 'next/document';

export declare const style: string;

export declare function getInitialProps({ renderPage }: { renderPage: any }): Promise<any>;

export declare class Document extends NextDocument {
  static getInitialProps: typeof getInitialProps;
  render(): JSX.Element;
}

export default Document;
```

**Comment by VGerris** [comment]
I changed it to the document.js file I found and then get :

Property getApplication does not exist on type 
 .
in vscodium.

I checked the source and see no obvious way to change it.
I thought this was all working a few days ago but I guess I missed some testing during upgrades. 
Still, any help is appreciated :)!

**Comment by VGerris** [comment]
mmm, I just removed the initialize function and its call to it and now it seems to work. Thank you !
