### ISSUE TITLE
Web support?

### ISSUE THREAD

**Issue by dragonfire1119** [nandorojo/dripsy#158]
Hello, this project looks nice. I'm very confused looking at the docs can this package be used with web divs, p ETC... The only examples I've seen are with react-native components. Also, do you have to use next.js?

Can this share the styling from web CSS, media queries <-> react-native?

Thanks

**Comment by nandorojo** [comment]
Hey, you might want to get a better understanding of how React Native Web works. This library is meant for React Native. React Native can also run in web browsers. Under the hood, it uses `div`s, but you never actually write those. Instead, you use `Text` and `View` and `Image` components.

There are no CSS media queries in React Native. Instead, you use the `Dimensions` API from `react-native` to render different styles based on screen size. Dripsy does this for you; just pass an array to any style, and configure your `theme.breakpoints` similar to Theme UI from React.

If you want pure CSS media queries for Web, while sharing code with React Native, you might want to check out Tamagui. Dripsy uses JS-first styling, since this is the recommendation from React Native in general, and requires less magic.

You do not need to use Next.js. It's just a popular option.

> Can this share the styling from web CSS, media queries <-> react-native?

Yes, but they aren't technically media queries under the hood. Any code you write with dripsy will work the same on Web, iOS and Android. Dripsy lets you design based on _screen size_, not platform.

I hope that answers your question.

**Comment by dragonfire1119** [comment]
@nandorojo Yes, you answered all the questions I was actually looking at react-native-web before you commented. Didn't know it existed. 🤯 Wow, that simplifies a lot of work. Already looking at integrating dripsy thanks for your time!

**Comment by nandorojo** [comment]
Great! Maybe I can clarify this in the docs.

**Comment by nandorojo** [comment]
I gave a talk about this at Next.js Conf 2021. I recommend checking it out: https://twitter.com/FernandoTheRojo/status/1453712622222729217?s=20

I break down how I built the [BeatGig](https://beatgig.com) app and website with one codebase, all with React Native.

**Comment by dragonfire1119** [comment]
> I gave a talk about this at Next.js Conf 2021. I recommend checking it out: https://twitter.com/FernandoTheRojo/status/1453712622222729217?s=20
> 
> 
> 
> I break down how I built the [BeatGig](https://beatgig.com) app and website with one codebase, all with React Native.

Cool, I will check it out! One quick question is there a way to let the user pick a color? Example a background color.

**Comment by saulamsal** [comment]
@dragonfire1119 yes, you can. Not sure how you'd like to do it? There are many ways. You could store in the react state, or async storage or store in the user's setting in your database and render that colour.
