### ISSUE TITLE
Does dripsy work like in-line styles and cause performance issues?

### ISSUE THREAD

**Issue by thegitparticle** [nandorojo/dripsy#168]
In-line styles in react-native are known for being not so performant as compared to using Stylesheet.create.

Maybe I'm missing something, but I'd like to know how does dripsy work behind the hood and does it cause any performance issues while issues while running on low spec devices if it is based on inline styles? (native apps, not web)

**Comment by nandorojo** [comment]
> In-line styles in react-native are known for being not so performant as compared to using Stylesheet.create.

This is actually a myth. They used to mention it on their docs, but StyleSheet.create does nothing. You can take a look at the source code. On Web, however, it is more optimal to use.

Under the hood, Dripsy deep compares styles, and in the last step, it uses StyleSheet.create before passing it to a component.

**Comment by thegitparticle** [comment]
That's amazing. 

> Dripsy deep memoizes styles, even when they’re written inline, and in the last step, it uses StyleSheet.create before passing it to a component

It answers my question

**Comment by JulianKingman** [comment]
Just to clarify... Stylesheet.create is generally called outside of the component, which is probably the main reason for the performance improvements (because it's not a newly instantiated object on every render). I assume styles are not compiled at build time, but during render, and the memoization is happening while running, and not ahead of time? What kind of overhead is there from the memoization? I'm guessing it's something that needs testing. This seems like a cool project, maybe I'll put together a benchmark to see if there's any notable difference. I've seen the performance question asked a few times in different places.

**Comment by thegitparticle** [comment]
@JulianKingman sure, looking forward for your benchmark analysis.
