### ISSUE TITLE
React warning: Did not expect server HTML to contain a <div> in <div>

### ISSUE THREAD

**Issue by mhaagens** [nandorojo/dripsy#76]
```Did not expect server HTML to contain a <div> in <div>```
Is this to be expected because of Fresnel rendering multiple divs or does it have an actual performance penalty?

**Comment by nandorojo** [comment]
Yeah it renders multiple nodes on the server. I'm releasing a workaround to that soon, see #56. For explanation on how fresnel divs works, see: https://github.com/nandorojo/dripsy/issues/34

**Comment by mhaagens** [comment]
Awesome, looks like a good solution!

**Comment by nandorojo** [comment]
As for the actual server warning from React, I’m not sure what that is. I use Next.js and don’t get that error. It makes me think the server and client are rendering something different, which is the exactly what our use of Fresnel tries to avoid. There are some solutions on stack overflow, so I’m not sure if this warning you got is due to Dripsy or not.

**Comment by mhaagens** [comment]
It only happens in development, not when I've built the project. Seems related to Fresnel, I've seen the issue pop up there as well. Unfortunately they didn't specify whether it constitutes an actual issue in terms of hydrating on the client.
