### ISSUE TITLE
justifyContent on Web not working correctly

### ISSUE THREAD

**Issue by abanobboles** [nandorojo/dripsy#98]
![CleanShot 2021-05-07 at 10 01 31](https://user-images.githubusercontent.com/9078953/117418015-39955d80-af1b-11eb-9e56-69020cc79588.png)

Hello, I want to make the text on the left and the logo on the right, it is working on Mobile Correctly.
With a View direction row and justify content with space between.
But on the web it is not working correctly, only if I delete the fresnel divs in browser it is working.
I don't know why there is this empty fresnel divs.

Please help me, Thank you.

```
 <View
      sx={{
        marginTop: [Constants.statusBarHeight, 15],
        mx: [20, 25],
        flexDirection: "row",
        alignItems: "center",
        flex: [0, 1],
        justifyContent: "space-between",
      }}
    >
      <Text
        sx={{
          color: ["primary"],
          fontSize: [22, 30],
          fontWeight: ["bold"],
        }}
      >
        Text
      </Text>

      <Image
        source={logo}
        style={{ resizeMode: "contain" }}
        sx={{
          height: [70],
          width: [70],
        }}
      />
    </View>
```

**Comment by nandorojo** [comment]
Hey, thanks for the issue. Yeah, I'm sorry this is a current shortcoming of the arrays on web. We use fresnel to support Server Side Rendering, which means that whenever an element has a responsive array, it's wrapped with a fresnel div.

There's extensive explanation about the behavior and reasoning here: https://github.com/nandorojo/dripsy/issues/34

I recommend reading that.

I'm actively working on a solution / different API, since I know it's a bit annoying. 

The current solution for your use-case is to add a `webContainerSx` prop to your `View`. I think if you just add `flex: [0, 1]`, it should solve it.

**Comment by nandorojo** [comment]
BTW, I would avoid using the arrays unless you need them to render fewer fresnel divs. So for your `Image`, for instance, since you don't use multiple sizes, I'd just pass `height: 70, width: 70`.

**Comment by nandorojo** [comment]
The solution I left works, it just unfortunately is a shortcoming of Dripsy's web API. `webContainerSx` is the current solution. It's sadly because the creator of React Native Web won't let us use `className`, even as an escape hatch. 🤷🏼‍♂️

So I'm going to close this for now. Know that I face this issue too, and am actively looking for better APIs.

**Comment by nandorojo** [comment]
I've solved this on the new version of Dripsy.

```sh
yarn add dripsy@canary
```

Please install that, thanks! See more at #101

**Comment by nandorojo** [comment]
The new version doesn't use Fresnel at all, it's much simpler, and faces none of these problems anymore.
